package com.thealer.telehealer.common.emptyState;

import android.content.Context;

import com.thealer.telehealer.R;
import com.thealer.telehealer.common.UserType;

/**
 * Created by Aswin on 20,November,2018
 */
public class EmptyStateUtil {

    public static String getTitle(Context context, String emptyType) {
        switch (emptyType) {
            case EmptyViewConstants.EMPTY_NO_NETWORK:
                return context.getString(R.string.EMPTY_NO_NETWORK_TITLE);
            case EmptyViewConstants.EMPTY_SERVER_DOWN:
                return context.getString(R.string.EMPTY_SERVER_DOWN_TITLE);
            case EmptyViewConstants.EMPTY_VITALS:
            case EmptyViewConstants.EMPTY_VITALS_WITH_BTN:
                return context.getString(R.string.EMPTY_VITALS_TITLE);
            case EmptyViewConstants.EMPTY_DOCUMENTS:
            case EmptyViewConstants.EMPTY_DOCUMENTS_WITH_BTN:
                return context.getString(R.string.EMPTY_DOCUMENTS_TITLE);
            case EmptyViewConstants.EMPTY_MISC:
            case EmptyViewConstants.EMPTY_MISC_WITH_BTN:
                return context.getString(R.string.EMPTY_MISC_TITLE);
            case EmptyViewConstants.EMPTY_PRESCRIPTION:
            case EmptyViewConstants.EMPTY_PRESCRIPTION_WITH_BTN:
                return context.getString(R.string.EMPTY_PRESCRIPTION_TITLE);
            case EmptyViewConstants.EMPTY_ORDER:
                return context.getString(R.string.EMPTY_ORDER_TITLE);
            case EmptyViewConstants.EMPTY_HISTORY:
            case EmptyViewConstants.EMPTY_HISTORY_WITH_BTN:
                return context.getString(R.string.EMPTY_HISTORY_TITLE);
            case EmptyViewConstants.EMPTY_APPOINTMENTS:
            case EmptyViewConstants.EMPTY_APPOINTMENTS_WITH_BTN:
                return context.getString(R.string.EMPTY_APPOINTMENTS_TITLE);
            case EmptyViewConstants.EMPTY_BP:
            case EmptyViewConstants.EMPTY_BP_WITH_BTN:
                return context.getString(R.string.EMPTY_BP_TITLE);
            case EmptyViewConstants.EMPTY_WEIGHT:
            case EmptyViewConstants.EMPTY_WEIGHT_WITH_BTN:
                return context.getString(R.string.EMPTY_WEIGHT_TITLE);
            case EmptyViewConstants.EMPTY_HEIGHT:
                return context.getString(R.string.EMPTY_HEIGHT_TITLE);
            case EmptyViewConstants.EMPTY_GULCOSE:
            case EmptyViewConstants.EMPTY_GULCOSE_WITH_BTN:
                return context.getString(R.string.EMPTY_GULCOSE_TITLE);
            case EmptyViewConstants.EMPTY_TEMPERATURE:
            case EmptyViewConstants.EMPTY_TEMPERATURE_WITH_BTN:
                return context.getString(R.string.EMPTY_TEMPERATURE_TITLE);
            case EmptyViewConstants.EMPTY_PULSE:
            case EmptyViewConstants.EMPTY_PULSE_WITH_BTN:
                return context.getString(R.string.EMPTY_PULSE_TITLE);
            case EmptyViewConstants.EMPTY_CHATS:
                return context.getString(R.string.EMPTY_CHATS_TITLE);
            case EmptyViewConstants.EMPTY_CALLS:
                return context.getString(R.string.EMPTY_CALLS_TITLE);
            case EmptyViewConstants.EMPTY_NOTIFICATIONS:
                return context.getString(R.string.EMPTY_NOTIFICATIONS_TITLE);
            case EmptyViewConstants.EMPTY_LABS:
            case EmptyViewConstants.EMPTY_LABS_WITH_BTN:
                return context.getString(R.string.EMPTY_LABS_TITLE);
            case EmptyViewConstants.EMPTY_SPECIALIST:
            case EmptyViewConstants.EMPTY_SPECIALIST_WITH_BTN:
                return context.getString(R.string.EMPTY_SPECIALIST_TITLE);
            case EmptyViewConstants.EMPTY_SEARCH:
                return context.getString(R.string.EMPTY_SEARCH_TITLE);
            case EmptyViewConstants.EMPTY_XRAY:
            case EmptyViewConstants.EMPTY_XRAY_WITH_BTN:
                return context.getString(R.string.EMPTY_XRAY_TITLE);
            case EmptyViewConstants.EMPTY_FORMS:
            case EmptyViewConstants.EMPTY_FORMS_WITH_BTN:
                return context.getString(R.string.EMPTY_FORMS_TITLE);
            case EmptyViewConstants.EMPTY_TRANSCRIPTS:
            case EmptyViewConstants.EMPTY_TRANSCRIPTS_WITH_BTN:
                return context.getString(R.string.EMPTY_TRANSCRIPTS_TITLE);
            case EmptyViewConstants.EMPTY_PATIENT_HISTORY:
                return context.getString(R.string.EMPTY_PATIENT_HISTORY_TITLE);
            case EmptyViewConstants.EMPTY_HEART_RATE:
            case EmptyViewConstants.EMPTY_HEART_RATE_WITH_BTN:
                return context.getString(R.string.EMPTY_HEART_RATE_TITLE);
            case EmptyViewConstants.EMPTY_PAYMENTS:
                return context.getString(R.string.EMPTY_PAYMENTS_TITLE);
            case EmptyViewConstants.EMPTY_CARDS:
                return context.getString(R.string.EMPTY_CARDS_TITLE);
            case EmptyViewConstants.EMPTY_PATIENT_SEARCH:
            case EmptyViewConstants.EMPTY_PATIENT:
            case EmptyViewConstants.EMPTY_PATIENT_WITH_BTN:
                return context.getString(R.string.EMPTY_PATIENT_TITLE);
            case EmptyViewConstants.EMPTY_DOCTOR:
            case EmptyViewConstants.EMPTY_DOCTOR_WITH_BTN:
                return context.getString(R.string.EMPTY_DOCTOR_TITLE);
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT:
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT_WITH_BTN:
                return context.getString(R.string.EMPTY_MEDICAL_ASSISTANT_TITLE);
            case EmptyViewConstants.EMPTY_CALL_LOGS:
                return context.getString(R.string.EMPTY_CALL_LOGS_TITLE);
            case EmptyViewConstants.EMPTY_VITAL_LOGS:
                return context.getString(R.string.EMPTY_VITAL_LOGS_TITLE);
            case EmptyViewConstants.EMPTY_DIET:
                return context.getString(R.string.EMPTY_DIET_TITLE);
            case EmptyViewConstants.EMPTY_DIET_LAST_WEEK:
                return context.getString(R.string.EMPTY_DIET_LAST_WEEK);
            case EmptyViewConstants.EMPTY_DIET_FROM_TO:
                return context.getString(R.string.EMPTY_DIET_FROM_TO);
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_SEARCH:
                return context.getString(R.string.EMPTY_DOCTOR_VITAL_SEARCH_TITLE);
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_LAST_WEEK:
                return context.getString(R.string.EMPTY_DOCTOR_VITAL_LAST_WEEK_TITLE);
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_TWO_WEEK:
                return context.getString(R.string.EMPTY_DOCTOR_VITAL_TWO_WEEK_TITLE);
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_MONTH:
                return context.getString(R.string.EMPTY_DOCTOR_VITAL_MONTH_TITLE);
            case EmptyViewConstants.EMPTY_FOOD_ITEMS:
                return context.getString(R.string.EMPTY_FOOD_ITEMS_TITLE);
            case EmptyViewConstants.EMPTY_RECEIVED_PENDING_INVITES:
            case EmptyViewConstants.EMPTY_SENT_PENDING_INVITES:
                return context.getString(R.string.EMPTY_PENDING_INVITES_TITLE);
            case EmptyViewConstants.EMPTY_BP_TRACK_VALUE:
                return context.getString(R.string.EMPTY_BP_TRACK_VALUE_TITLE);
            case EmptyViewConstants.EMPTY_STETHOSCOPE:
            case EmptyViewConstants.EMPTY_STETHOSCOPE_WITH_BTN:
                return context.getString(R.string.EMPTY_STETHOSCOPE_TITLE);
            case EmptyViewConstants.EMPTY_VITAL_FROM_TO:
                return context.getString(R.string.EMPTY_VITAL_FROM_TO);
            case EmptyViewConstants.EMPTY_UNCONNECTED_USER:
                return context.getString(R.string.EMPTY_UNCONNECTED_USER);
            case EmptyViewConstants.EMPTY_GOOGLE_FIT_SOURCE:
                return context.getString(R.string.no_source_found);
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEOS:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_WITH_BTN:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_NEW:
                return context.getString(R.string.no_educational_video);
            default:
                return null;
        }
    }

    public static String getMessage(Context context, String emptyType) {
        switch (emptyType) {
            case EmptyViewConstants.EMPTY_NO_NETWORK:
                return context.getString(R.string.EMPTY_NO_NETWORK_MESSAGE);
            case EmptyViewConstants.EMPTY_SERVER_DOWN:
                return context.getString(R.string.EMPTY_SERVER_DOWN_MESSAGE);
            case EmptyViewConstants.EMPTY_VITALS:
                return context.getString(R.string.EMPTY_VITALS_MESSAGE);
            case EmptyViewConstants.EMPTY_VITALS_WITH_BTN:
                return context.getString(R.string.EMPTY_VITALS_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_DOCUMENTS:
                return context.getString(R.string.EMPTY_DOCUMENTS_MESSAGE);
            case EmptyViewConstants.EMPTY_DOCUMENTS_WITH_BTN:
                return context.getString(R.string.EMPTY_DOCUMENTS_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_MISC:
                return context.getString(R.string.EMPTY_MISC_MESSAGE);
            case EmptyViewConstants.EMPTY_MISC_WITH_BTN:
                return context.getString(R.string.EMPTY_MISC_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_ORDER:
                return context.getString(R.string.EMPTY_ORDER_MESSAGE);
            case EmptyViewConstants.EMPTY_PRESCRIPTION:
                return context.getString(R.string.EMPTY_PRESCRIPTION_MESSAGE);
            case EmptyViewConstants.EMPTY_PRESCRIPTION_WITH_BTN:
                return context.getString(R.string.EMPTY_PRESCRIPTION_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_HISTORY:
            case EmptyViewConstants.EMPTY_HISTORY_WITH_BTN:
                return context.getString(R.string.EMPTY_HISTORY_MESSAGE);
            case EmptyViewConstants.EMPTY_APPOINTMENTS:
                return context.getString(R.string.EMPTY_APPOINTMENTS_MESSAGE);
            case EmptyViewConstants.EMPTY_APPOINTMENTS_WITH_BTN:
                return context.getString(R.string.EMPTY_APPOINTMENTS_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_BP:
                return context.getString(R.string.EMPTY_BP_MESSAGE);
            case EmptyViewConstants.EMPTY_BP_WITH_BTN:
                return context.getString(R.string.EMPTY_BP_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_WEIGHT:
                return context.getString(R.string.EMPTY_WEIGHT_MESSAGE);
            case EmptyViewConstants.EMPTY_WEIGHT_WITH_BTN:
                return context.getString(R.string.EMPTY_WEIGHT_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_HEIGHT:
                return context.getString(R.string.EMPTY_HEIGHT_MESSAGE);
            case EmptyViewConstants.EMPTY_GULCOSE:
                return context.getString(R.string.EMPTY_GULCOSE_MESSAGE);
            case EmptyViewConstants.EMPTY_GULCOSE_WITH_BTN:
                return context.getString(R.string.EMPTY_GULCOSE_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_TEMPERATURE:
                return context.getString(R.string.EMPTY_TEMPERATURE_MESSAGE);
            case EmptyViewConstants.EMPTY_TEMPERATURE_WITH_BTN:
                return context.getString(R.string.EMPTY_TEMPERATURE_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_PULSE:
                return context.getString(R.string.EMPTY_PULSE_MESSAGE);
            case EmptyViewConstants.EMPTY_PULSE_WITH_BTN:
                return context.getString(R.string.EMPTY_PULSE_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_CHATS:
                return context.getString(R.string.EMPTY_CHATS_MESSAGE);
            case EmptyViewConstants.EMPTY_CALLS:
                return context.getString(R.string.EMPTY_CALLS_MESSAGE);
            case EmptyViewConstants.EMPTY_NOTIFICATIONS:
                return context.getString(R.string.EMPTY_NOTIFICATIONS_MESSAGE);
            case EmptyViewConstants.EMPTY_LABS:
                return context.getString(R.string.EMPTY_LABS_MESSAGE);
            case EmptyViewConstants.EMPTY_LABS_WITH_BTN:
                return context.getString(R.string.EMPTY_LABS_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_SPECIALIST:
                return context.getString(R.string.EMPTY_SPECIALIST_MESSAGE);
            case EmptyViewConstants.EMPTY_SPECIALIST_WITH_BTN:
                return context.getString(R.string.EMPTY_SPECIALIST_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_SEARCH:
                return context.getString(R.string.EMPTY_SEARCH_MESSAGE);
            case EmptyViewConstants.EMPTY_XRAY:
                return context.getString(R.string.EMPTY_XRAY_MESSAGE);
            case EmptyViewConstants.EMPTY_XRAY_WITH_BTN:
                return context.getString(R.string.EMPTY_XRAY_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_FORMS:
                return context.getString(R.string.EMPTY_FORMS_MESSAGE);
            case EmptyViewConstants.EMPTY_FORMS_WITH_BTN:
                return context.getString(R.string.EMPTY_FORMS_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_TRANSCRIPTS:
            case EmptyViewConstants.EMPTY_TRANSCRIPTS_WITH_BTN:
                return context.getString(R.string.EMPTY_TRANSCRIPTS_MESSAGE);
            case EmptyViewConstants.EMPTY_PATIENT_HISTORY:
                return context.getString(R.string.EMPTY_PATIENT_HISTORY_MESSAGE);
            case EmptyViewConstants.EMPTY_HEART_RATE:
                return context.getString(R.string.EMPTY_HEART_RATE_MESSAGE);
            case EmptyViewConstants.EMPTY_HEART_RATE_WITH_BTN:
                return context.getString(R.string.EMPTY_HEART_RATE_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_PAYMENTS:
                return context.getString(R.string.EMPTY_PAYMENTS_MESSAGE);
            case EmptyViewConstants.EMPTY_CARDS:
                return context.getString(R.string.EMPTY_CARDS_MESSAGE);
            case EmptyViewConstants.EMPTY_PATIENT:
                return context.getString(R.string.EMPTY_PATIENT_MESSAGE);
            case EmptyViewConstants.EMPTY_PATIENT_WITH_BTN:
                return context.getString(R.string.EMPTY_PATIENT_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_PATIENT_SEARCH:
                return context.getString(R.string.EMPTY_PATIENT_SEARCH_MESSAGE);
            case EmptyViewConstants.EMPTY_DOCTOR:
                return context.getString(R.string.EMPTY_DOCTOR_MESSAGE);
            case EmptyViewConstants.EMPTY_DOCTOR_WITH_BTN:
                return context.getString(R.string.EMPTY_DOCTOR_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT:
                return context.getString(R.string.EMPTY_MEDICAL_ASSISTANT_MESSAGE);
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT_WITH_BTN:
                return context.getString(R.string.EMPTY_MEDICAL_ASSISTANT_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_CALL_LOGS:
                return context.getString(R.string.EMPTY_CALL_LOGS_MESSAGE);
            case EmptyViewConstants.EMPTY_VITAL_LOGS:
                return context.getString(R.string.EMPTY_VITAL_LOGS_MESSAGE);
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_SEARCH:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_LAST_WEEK:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_TWO_WEEK:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_MONTH:
                return context.getString(R.string.EMPTY_DOCTOR_VITAL_SEARCH_MESSAGE);
            case EmptyViewConstants.EMPTY_DIET:
            case EmptyViewConstants.EMPTY_DIET_LAST_WEEK:
            case EmptyViewConstants.EMPTY_DIET_FROM_TO:
                return context.getString(R.string.EMPTY_DIET_MESSAGE);
            case EmptyViewConstants.EMPTY_FOOD_ITEMS:
                return context.getString(R.string.EMPTY_FOOD_ITEMS_MESSAGE);
            case EmptyViewConstants.EMPTY_RECEIVED_PENDING_INVITES:
                return context.getString(R.string.EMPTY_RECEIVED_PENDING_INVITES_MESSAGE);
            case EmptyViewConstants.EMPTY_SENT_PENDING_INVITES:
                return context.getString(R.string.EMPTY_SENT_PENDING_INVITES_MESSAGE);
            case EmptyViewConstants.EMPTY_BP_TRACK_VALUE:
                if (UserType.isUserPatient()) {
                    return context.getString(R.string.EMPTY_BP_TRACK_VALUE_MESSAGE);
                } else {
                    return "";
                }
            case EmptyViewConstants.EMPTY_STETHOSCOPE:
                return context.getString(R.string.EMPTY_STETHOSCOPE_MESSAGE);
            case EmptyViewConstants.EMPTY_STETHOSCOPE_WITH_BTN:
                return context.getString(R.string.EMPTY_STETHOSCOPE_WITH_BTN_MESSAGE);
            case EmptyViewConstants.EMPTY_UNCONNECTED_USER:
                return context.getString(R.string.EMPTY_UNCONNECTED_USER_MESSAGE);
            case EmptyViewConstants.EMPTY_GOOGLE_FIT_SOURCE:
                return context.getString(R.string.no_source_found_message);
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEOS:
                return context.getString(R.string.empty_educational_message);
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER:
                return context.getString(R.string.empty_educational_message_1);
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_WITH_BTN:
                return context.getString(R.string.empty_educational_message);
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_NEW:
                return context.getString(R.string.empty_educational_new);
            default:
                return null;
        }
    }

    public static int getImage(String emptyType) {
        switch (emptyType) {
            case EmptyViewConstants.EMPTY_NO_NETWORK:
            case EmptyViewConstants.EMPTY_SERVER_DOWN:
                return R.drawable.emptystate_no_network;
            case EmptyViewConstants.EMPTY_VITALS:
            case EmptyViewConstants.EMPTY_VITALS_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_DOCUMENTS:
            case EmptyViewConstants.EMPTY_DOCUMENTS_WITH_BTN:
                return R.drawable.emptystate_no_document;
            case EmptyViewConstants.EMPTY_MISC:
            case EmptyViewConstants.EMPTY_MISC_WITH_BTN:
                return R.drawable.emptystate_misc;
            case EmptyViewConstants.EMPTY_PRESCRIPTION:
            case EmptyViewConstants.EMPTY_PRESCRIPTION_WITH_BTN:
            case EmptyViewConstants.EMPTY_ORDER:
                return R.drawable.emptystate_no_prescription;
            case EmptyViewConstants.EMPTY_HISTORY:
            case EmptyViewConstants.EMPTY_HISTORY_WITH_BTN:
                return R.drawable.emptystate_no_history;
            case EmptyViewConstants.EMPTY_APPOINTMENTS:
            case EmptyViewConstants.EMPTY_APPOINTMENTS_WITH_BTN:
                return R.drawable.emptystate_no_schedule;
            case EmptyViewConstants.EMPTY_BP:
            case EmptyViewConstants.EMPTY_BP_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_WEIGHT:
            case EmptyViewConstants.EMPTY_WEIGHT_WITH_BTN:
            case EmptyViewConstants.EMPTY_HEIGHT:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_GULCOSE:
            case EmptyViewConstants.EMPTY_GULCOSE_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_TEMPERATURE:
            case EmptyViewConstants.EMPTY_TEMPERATURE_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_PULSE:
            case EmptyViewConstants.EMPTY_PULSE_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_CHATS:
                return R.drawable.emptystate_no_patient;
            case EmptyViewConstants.EMPTY_CALLS:
                return R.drawable.emptystate_no_calls;
            case EmptyViewConstants.EMPTY_NOTIFICATIONS:
                return R.drawable.emptystate_no_notification;
            case EmptyViewConstants.EMPTY_LABS:
            case EmptyViewConstants.EMPTY_LABS_WITH_BTN:
                return R.drawable.emptystate_doctor_no_lab;
            case EmptyViewConstants.EMPTY_DOCTOR:
            case EmptyViewConstants.EMPTY_DOCTOR_WITH_BTN:
            case EmptyViewConstants.EMPTY_SPECIALIST:
            case EmptyViewConstants.EMPTY_SPECIALIST_WITH_BTN:
                return R.drawable.emptystate_no_doctor;
            case EmptyViewConstants.EMPTY_SEARCH:
                return R.drawable.emptystate_no_search;
            case EmptyViewConstants.EMPTY_XRAY:
            case EmptyViewConstants.EMPTY_XRAY_WITH_BTN:
                return R.drawable.emptystate_no_xray;
            case EmptyViewConstants.EMPTY_FORMS:
            case EmptyViewConstants.EMPTY_FORMS_WITH_BTN:
            case EmptyViewConstants.EMPTY_PATIENT_HISTORY:
                return R.drawable.emptystate_no_forms;
            case EmptyViewConstants.EMPTY_TRANSCRIPTS:
            case EmptyViewConstants.EMPTY_TRANSCRIPTS_WITH_BTN:
                return R.drawable.emptystate_no_transcribe;
            case EmptyViewConstants.EMPTY_HEART_RATE:
            case EmptyViewConstants.EMPTY_HEART_RATE_WITH_BTN:
            case EmptyViewConstants.EMPTY_STETHOSCOPE:
            case EmptyViewConstants.EMPTY_STETHOSCOPE_WITH_BTN:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_PAYMENTS:
                return R.drawable.emptystate_credit_card;
            case EmptyViewConstants.EMPTY_CARDS:
                return R.drawable.emptystate_credit_card;
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_SEARCH:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_LAST_WEEK:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_TWO_WEEK:
            case EmptyViewConstants.EMPTY_DOCTOR_VITAL_MONTH:
            case EmptyViewConstants.EMPTY_PATIENT_SEARCH:
            case EmptyViewConstants.EMPTY_PATIENT:
            case EmptyViewConstants.EMPTY_PATIENT_WITH_BTN:
                return R.drawable.emptystate_no_patient;
            case EmptyViewConstants.EMPTY_CALL_LOGS:
                return R.drawable.emptystate_no_calls;
            case EmptyViewConstants.EMPTY_VITAL_LOGS:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT:
            case EmptyViewConstants.EMPTY_MEDICAL_ASSISTANT_WITH_BTN:
                return R.drawable.emptystate_no_medical_assistant;
            case EmptyViewConstants.EMPTY_DIET:
            case EmptyViewConstants.EMPTY_DIET_LAST_WEEK:
            case EmptyViewConstants.EMPTY_DIET_FROM_TO:
            case EmptyViewConstants.EMPTY_FOOD_ITEMS:
                return R.drawable.emptystate_diet;
            case EmptyViewConstants.EMPTY_RECEIVED_PENDING_INVITES:
            case EmptyViewConstants.EMPTY_SENT_PENDING_INVITES:
            case EmptyViewConstants.EMPTY_UNCONNECTED_USER:
                return R.drawable.emptystate_pending_invites;
            case EmptyViewConstants.EMPTY_BP_TRACK_VALUE:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_GOOGLE_FIT_SOURCE:
                return R.drawable.emptystate_no_vitals;
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEOS:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_WITH_BTN:
            case EmptyViewConstants.EMPTY_EDUCATIONAL_VIDEO_ORDER_NEW:
                return R.drawable.emptystate_educational_video;
            default:
                return 0;
        }
    }
}
